baseurl         = ""
theme = "hugo-sp-minimal"
languageCode    = "en-us"
title           = "SP-Minimal"
disqusShortname = ""
paginate        = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title       = "Onkobioloogia"
  subtitle    = "Vähi molekulaarsed alused"
  copyright   = ""
  authorImage = "Next-generation_Hallmarks_of_Cancer_wheel_with_labels.svg.png"

  #"single" or "multi"
  renderType = "single"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = "UA-58708073-4"

  name = "TP"
  description = "Onkobioloogia loengukursuse materjalid."
  pageNotFoundTitle = "404 - Page not found"

